Fix unassigned variable
chipsec/chipsec pull request #1190
Opened 2021-05-18 17:22 UTC by BrentHoltsclaw

Signed-off-by: brentholtsclaw <brent.holtsclaw@intel.com>

2021-05-19 03:09 UTC, npmitche approved these changes

2021-05-19 18:07 UTC, Sae86 approved these changes

2021-05-20 17:29 UTC, iherna2 requested changes
line 193 should be changed to use 'preserve' variable as well

2021-05-25 23:21 UTC, npmitche approved these changes

2021-05-27 17:44 UTC, merged