Add usage documentation to variables.py
chipsec/chipsec pull request #1434
Opened 2022-04-12 23:20 UTC by frinzell

- Add and clarify module usage for sphinx documentation
- Minor code clean up

Signed-off-by: Frinzell, Aaron <aaron.frinzell@intel.com>

2022-04-21 20:00 UTC, dscott90 reviewed
(new)line 81 should be separated after 'else:'

2022-04-22 15:23 UTC, dscott90 requested changes
Remove comment lines 183-186, similar to https://github.com/chipsec/chipsec/pull/1432/commits/1a9ccbbc2632ff916c7d4807760d9a3203f15943

2022-04-25 16:44 UTC, dscott90 approved these changes

2022-04-25 20:59 UTC, kevinsun49 approved these changes

2022-04-25 22:03 UTC, Sae86 approved these changes

2022-04-25 22:03 UTC, merged