Decompress changes - remove helper dependencies
chipsec/chipsec pull request #1487
Opened 2022-06-02 00:59 UTC by BrentHoltsclaw

lzma can be imported within python3
brotli is a pip package
Modified tianocompress to build using setuptools
Moved functionality from helper to hal level for decompression
Removed dependencies of decompress that use UEFI HAL object
Cleanup of dead code resulting in the changes

2022-12-01 17:11 UTC, npmitche approved these changes

2022-12-01 23:52 UTC, npmitche requested changes

2022-12-01 23:52 UTC, npmitche commented on chipsec/hal/uefi_compression.py
> +                    data = lzma.decompress(compressed_data)
Needs hack.

2022-12-05 18:45 UTC, npmitche approved these changes

2022-12-06 00:31 UTC, frinzell approved these changes

2022-12-06 00:34 UTC, merged