Better docstring formatting in smm_dma.py
chipsec/chipsec pull request #1548
Opened 2022-07-29 20:28 UTC by frinzell

- Should address formatting quirk in chipsec-manual.pdf
- Possible dead link (keep as an archive?)

Signed-off-by: Frinzell, Aaron <aaron.frinzell@intel.com>

2022-08-04 22:45 UTC, dscott90 approved these changes

2022-08-24 20:26 UTC, npmitche requested changes

2022-08-24 20:26 UTC, npmitche commented on chipsec/modules/common/smm_dma.py
> +    - `Programmed I/O accesses: a threat to Virtual Machine Monitors? <http://www.ssi.gouv.fr/archive/fr/sciences/fichiers/lti/pacsec2007-duflot-papier.pdf>`_ (broken?)
Should probably just remove it.

2022-08-26 16:45 UTC, npmitche approved these changes

2022-08-26 16:45 UTC, merged