Decouple chipsec_main from logger
chipsec/chipsec pull request #1608
Opened 2022-11-22 18:28 UTC by BrentHoltsclaw

Remove start_test from logger
Enhance TestCase class to add start_test funtionality Change logic within run_loaded modules to use TestCase opposed to logger Add fstring to testcase.py
Add Type information to testcase.py

Signed-off-by: brentholtsclaw <brent.holtsclaw@intel.com>

2023-01-12 20:32 UTC, frinzell requested changes

2023-01-12 20:32 UTC, frinzell commented on chipsec/testcase.py
> +                summary_dict[k] = '{summary[k]:d}'
Needs to be an fstring

2023-01-12 20:32 UTC, frinzell commented on chipsec/testcase.py
> +    def xml_full(self, name) -> str:
`name` needs a type hint

2023-01-12 20:32 UTC, frinzell commented on chipsec/testcase.py
> +        text = f'\n[*] running module: {self.name}'
Please preserve 'Running' chaptalization.  `[*] Running module:`

2023-01-12 23:55 UTC, npmitche commented on chipsec/testcase.py
> +class ChipsecResults():
empty parentheses.

2023-01-13 01:25 UTC, npmitche approved these changes

2023-01-18 14:30 UTC, jun2zhou commented
@BrentHoltsclaw  I compare the log with previous version, the alignment and color changed.
<img width="875" alt="image" src="https://user-images.githubusercontent.com/111552005/213197889-5ffc7df9-4f9d-4dd3-80b8-4d3aad2097df.png">

2023-01-18 16:59 UTC, npmitche commented
> @BrentHoltsclaw I compared the log with previous version, the alignment and color changed. <img alt="image" width="875" src="https://user-images.githubusercontent.com/111552005/213197889-5ffc7df9-4f9d-4dd3-80b8-4d3aad2097df.png">

I'm not seeing this:
![Screenshot 2023-01-18 090710](https://user-images.githubusercontent.com/40474174/213245824-84d9df2c-bb70-4de2-a270-ae3a8af6b259.png)
![Screenshot from 2023-01-18 08-41-30](https://user-images.githubusercontent.com/40474174/213245870-ab0531ba-47a0-4007-b257-795d6a49811a.png)

 Though I am seeing an issue with logger().error() that I'll need to look into:
```
WARNING: NOT APPLICABLE: chipsec.modules.common.smm
[CHIPSEC] Modules with exceptions 2:
Traceback (most recent call last):
  File "C:\Users\Nathaniel\Desktop\chipsec-loggingchanges\chipsec_main.py", line 489, in <module>
    sys.exit(main())
  File "C:\Users\Nathaniel\Desktop\chipsec-loggingchanges\chipsec_main.py", line 484, in main
    return chipsecMain.main()
  File "C:\Users\Nathaniel\Desktop\chipsec-loggingchanges\chipsec_main.py", line 472, in main
    modules_failed = self.run_all_modules()
  File "C:\Users\Nathaniel\Desktop\chipsec-loggingchanges\chipsec_main.py", line 373, in run_all_modules
    return self.run_loaded_modules()
  File "C:\Users\Nathaniel\Desktop\chipsec-loggingchanges\chipsec_main.py", line 343, in run_loaded_modules
    results.print_summary(runtime)
  File "C:\Users\Nathaniel\Desktop\chipsec-loggingchanges\chipsec\testcase.py", line 293, in print_summary
    logger().error(mod)
AttributeError: 'Logger' object has no attribute 'error'
```

2023-01-18 17:01 UTC, BrentHoltsclaw commented
@jun2zhou can you provide more information on how you created this?  I have not been able to create a similar error.

2023-01-18 17:04 UTC, npmitche requested changes

2023-01-18 17:04 UTC, npmitche commented on chipsec/testcase.py
> +                        logger().error(mod)
should be `logger().log_error(mod)

2023-01-18 17:06 UTC, npmitche approved these changes

2023-01-19 00:53 UTC, dscott90 approved these changes

2023-01-19 01:12 UTC, merged