Change logger to use formatter
chipsec/chipsec pull request #1646
Opened 2023-01-18 01:43 UTC by BrentHoltsclaw

Add two formatting classes for stream and logfile

Add filter to apply additional labels based upon logging level

Signed-off-by: brentholtsclaw <brent.holtsclaw@intel.com>

2023-01-18 22:22 UTC, npmitche requested changes

2023-01-18 22:50 UTC, npmitche commented
I'm seeing what @jun2zhou posted on PR #1608:
 https://github.com/chipsec/chipsec/pull/1608#issuecomment-1387166955 

with this PR. Is that expected?

2023-01-18 23:23 UTC, npmitche requested changes

2023-01-18 23:23 UTC, npmitche commented on chipsec/logger.py
> +        self.chipsecLogger.info(text, level.INFO, 'BLUE')
```suggestion
        self.log(text, level.INFO, 'BLUE')
```

2023-01-18 23:23 UTC, npmitche commented on chipsec/logger.py
> +        logFormatter = chipsecLogFormatter('%(additional)s %(message)s')
```suggestion
        logFormatter = chipsecLogFormatter('%(additional)s%(message)s')
```
Additional space adds a space to the beginning if there's no prefix.

2023-01-18 23:23 UTC, npmitche commented on chipsec/logger.py
> +        streamFormatter = chipsecStreamFormatter('%(additional)s %(message)s')
Same as above.

2023-01-18 23:56 UTC, npmitche requested changes

2023-01-18 23:56 UTC, npmitche commented on chipsec/logger.py
> +    def __init__(self, fmt: Optional[T] = ..., datefmt: Optional[T] = ..., style='%') -> None:
```suggestion
    def __init__(self, fmt: Optional[str] = ..., datefmt: Optional[str] = ..., style='%') -> None:
```
Sorry, T was just a placeholder. Please keep the correct type. Everything else is looking good!

2023-01-18 23:56 UTC, npmitche commented on chipsec/logger.py
> +    def __init__(self, fmt: Optional[T] = ..., datefmt: Optional[T] = ..., style='%') -> None:
```suggestion
    def __init__(self, fmt: Optional[str] = ..., datefmt: Optional[str] = ..., style='%') -> None:
```

2023-01-19 00:29 UTC, npmitche approved these changes

2023-01-19 01:07 UTC, dscott90 approved these changes

2023-01-19 21:22 UTC, merged