Add rpl config
chipsec/chipsec pull request #1653
Opened 2023-01-24 01:55 UTC by dscott90

2023-01-24 21:16 UTC, frinzell commented on chipsec/cfg/8086/rpl.xml
> +        <field name="PHMB" bit="20" size="19" desc="Protected High-Memory Base"/>
Sizes for `VTBAR_PHMBASE.PHMB` and `VTBAR_PHMLIMIT.PHML` might be off.

2023-01-24 21:43 UTC, npmitche requested changes

2023-01-24 21:43 UTC, npmitche commented on chipsec/cfg/8086/rpl.xml
> +<register>
```suggestion
<registers>
```

2023-01-25 16:10 UTC, npmitche approved these changes

2023-01-25 16:19 UTC, npmitche commented on chipsec/cfg/8086/rpl.xml
> +</registers>
Missing the ending `</configuration>`

2023-01-25 18:12 UTC, npmitche approved these changes

2023-01-25 19:05 UTC, merged