fstring updates to uefi_common.py
chipsec/chipsec pull request #1695
Opened 2023-02-21 20:28 UTC by frinzell

2023-02-22 01:56 UTC, jun2zhou approved these changes

2023-02-23 02:04 UTC, dscott90 requested changes

2023-02-23 02:04 UTC, dscott90 commented on chipsec/hal/uefi_common.py
> +  UninstallProtocolInterface         : 0x{self.UninstallMultipleProtocolInterfaces:016X}
```suggestion
  UninstallProtocolInterface         : 0x{self.UninstallProtocolInterface:016X}
```

2023-02-23 15:31 UTC, frinzell commented on chipsec/hal/uefi_common.py
> +  UninstallProtocolInterface         : 0x{self.UninstallMultipleProtocolInterfaces:016X}
Good find!

2023-02-23 17:33 UTC, merged