Type Hint and fstring updates to spi_uefi.py
chipsec/chipsec pull request #1714
Opened 2023-03-06 22:07 UTC by frinzell

- Add Type Hints
- Move to fstrings
- Minor clean up

2023-03-08 18:03 UTC, dscott90 requested changes

2023-03-08 18:34 UTC, frinzell commented on chipsec/hal/spi_uefi.py
> +                        logger().log(f'Replacing UEFI file with GUID={fwbin.Guid} at offset={len(uefi_file):08X}, new size: {CurFileOffset:d}, old size: {fwbin.Size:d}, size change: {FvLengthChange:d
Good find!

2023-03-15 17:47 UTC, npmitche approved these changes

2023-03-20 22:28 UTC, dscott90 approved these changes

2023-03-20 23:39 UTC, merged