f'string updates to vmm hv folder in tools
chipsec/chipsec pull request #1746
Opened 2023-04-17 23:14 UTC by Sae86

2023-04-18 23:42 UTC, npmitche approved these changes
We should circle back around to look at the `return` call in custom_fuzzing line 392 in tools/vmm/hv/hypercall.py.

2023-04-20 16:36 UTC, dscott90 requested changes

2023-04-20 17:09 UTC, npmitche commented on chipsec/modules/tools/vmm/hv/hypercall.py
> +            self.msg(f'Hypercall: {hcname} ')
Sara was only changing to f'strings. I agree this should be looked at, but doesn't have to be this PR.

2023-04-20 17:14 UTC, dscott90 approved these changes

2023-04-20 22:39 UTC, frinzell approved these changes

2023-04-24 21:03 UTC, merged