Type Hint and f-string updates to linuxhelper.py
chipsec/chipsec pull request #1752
Opened 2023-04-20 20:38 UTC by frinzell

- Add Type Hints
- Move to f-strings
- Some code clean-up

2023-04-24 20:41 UTC, npmitche requested changes

2023-04-24 20:41 UTC, npmitche commented on chipsec/helper/linux/linuxhelper.py
> +        return False
This should stay as unimplemented. In UEFI Shell, I can see this just returning False. But in Linux it is possible to have it, we just haven't implemented the check for it.

2023-04-25 15:28 UTC, npmitche approved these changes

2023-04-25 15:59 UTC, Sae86 approved these changes

2023-04-25 16:10 UTC, merged