f'string updates to vmm subfolders in tools
chipsec/chipsec pull request #1757
Opened 2023-04-24 17:15 UTC by Sae86

2023-04-24 18:39 UTC, npmitche requested changes

2023-04-24 18:39 UTC, npmitche commented on chipsec/modules/tools/vmm/vbox/vbox_crash_apicbase.py
> +        self.logger.log('[*] Writing 0x{apicbase_msr:016X} to IA32_APIC_BASE MSR..')
Forgot the leading `f`

2023-04-25 22:00 UTC, frinzell approved these changes

2023-04-25 22:26 UTC, npmitche approved these changes

2023-04-25 22:26 UTC, merged