Add typehints and fstrings to decode_cmd.py
chipsec/chipsec pull request #1847
Opened 2023-06-09 22:47 UTC by dscott90

2023-06-11 09:20 UTC, fishilico commented on chipsec/utilcmd/decode_cmd.py
> +    def decode_rom(self) -> bool:
This CodeQL notice is caused by the fact that a `return True` seems to be missing from the end of this function.

2023-06-13 23:19 UTC, npmitche commented on chipsec/utilcmd/decode_cmd.py
> +from typing import Optional
Should clean this up.

2023-06-13 23:19 UTC, npmitche requested changes
Clean up codeQL alerts.

2023-06-14 19:11 UTC, fishilico requested changes

2023-06-14 19:11 UTC, fishilico commented on chipsec/utilcmd/decode_cmd.py
> +        return True
This `return True` needs to be moved a few lines down, where the function ends (line 118)

2023-06-14 19:47 UTC, fishilico approved these changes

2023-06-14 19:51 UTC, npmitche approved these changes

2023-06-14 23:38 UTC, merged