Add return codes support to vmm.venom and wsmt in tools
chipsec/chipsec pull request #1949
Opened 2023-09-24 18:10 UTC by Sae86

2023-09-27 21:01 UTC, npmitche requested changes

2023-09-27 21:01 UTC, npmitche commented on chipsec/modules/tools/wsmt.py
> +    def __init__(self):
Should not have two __init__ functions.

2023-09-28 18:28 UTC, npmitche approved these changes

2023-09-28 20:51 UTC, frinzell approved these changes

2023-09-29 04:23 UTC, merged