Add return codes to spd_wd, spi_access, spi_desc, spi_fdopss and spi_…
chipsec/chipsec pull request #1976
Opened 2023-11-02 20:08 UTC by Sae86

…lock

2023-11-07 00:25 UTC, dscott90 approved these changes

2023-11-09 00:17 UTC, npmitche approved these changes

2023-11-10 00:24 UTC, npmitche commented
@Sae86 Can you look at why spi_lock is erroring but passing?

2023-11-13 23:05 UTC, npmitche requested changes
Please review test issue.

2023-11-17 19:50 UTC, npmitche approved these changes

2023-11-21 00:38 UTC, merged