Add typehints and fstrings to common modules
chipsec/chipsec pull request #1982
Opened 2023-11-09 21:28 UTC by dscott90

2023-11-13 22:44 UTC, npmitche approved these changes

2023-11-13 23:02 UTC, npmitche commented on chipsec/modules/common/rtclock.py
> +    def run(self, *module_argv: str) -> int:
This I think is causing tests to fail. All of these should be:
```suggestion
    def run(self, module_argv: List[str]) -> int:
```
I think

2023-11-13 23:04 UTC, npmitche requested changes
The run function's args seems like it needs to remove the `*` and add `List[str]` instead of `str`. Needs some more testing.

2023-11-17 19:52 UTC, npmitche approved these changes

2023-11-21 00:32 UTC, jun2zhou approved these changes

2023-12-01 17:35 UTC, merged