Return status in all write port functions
chipsec/chipsec pull request #2075
Opened 2024-03-07 22:49 UTC by Sae86

Fixes #625

2024-03-11 23:02 UTC, dscott90 approved these changes

2024-03-12 19:11 UTC, npmitche approved these changes

2024-03-12 19:11 UTC, npmitche requested changes
Please change the type hint return value from None.

2024-03-18 22:47 UTC, npmitche approved these changes

2024-03-18 23:38 UTC, merged