Add SMI enumeration mode to the smm_ptr module
chipsec/chipsec pull request #2141
Opened 2024-04-20 16:37 UTC by cpey

The following pull request extends the `smm_ptr` module by adding an additional
mode called `scan`.

The goal of the `scan` mode is to identify SMIs that trigger time-consuming
code paths by measuring their execution time. This new mode operates similarly
to the fuzz mode and uses a new syscall that returns the SMI execution time.
With the intention to minimize system crashes, its operation bails out from the
currently scanned SMI code when an SMI taking considerably longer is
encountered or memory changes have been detected.

A time-consuming SMI is referred to as 'outlier' in the implementation, and
determined by the configuration option `OUTLIER_THRESHOLD`.

When an 'outlier' is identified, a message similar to the one shown below is
added to the output log.

~~~
[!] SCANNED: SMI# 57 average 785652 checked 1
    Identified outlier: duration 2456476 code 57 data 00 (rax=B284F000 rbx=B284F000 rcx=00, rdx=B284F000 rsi=B284F000 rdi=B284F000)
~~~

The message informs about the average CPU counts for that SMI code, the number
of SMIs executed for that code (scanning for data and rcx values) until the
first outlier is found or a memory change detected (in `checked`), followed by
information about the outlier.

When no outlier is found, the log message does not include the 'outlier'
information.

~~~
[*] SCANNED: SMI# 58 average 759601 checked 4096
~~~

At the end of the report, it lists the number of long-running SMIs found,
followed by the remaining smm_ptr results.

~~~
[+] <<< Done: found 5 long-running SMIs
[-] <<< Done: found 4 potential occurrences of unchecked input pointers

[CHIPSEC] ***************************  SUMMARY  ***************************
[CHIPSEC] Time elapsed            547.306
[CHIPSEC] Modules total           1
[CHIPSEC] Modules failed to run   0:
[CHIPSEC] Modules passed          0:
[CHIPSEC] Modules information     0:
[CHIPSEC] Modules failed          1:
[-] FAILED: chipsec.modules.tools.smm.smm_ptr
[CHIPSEC] Modules with warnings   0:
[CHIPSEC] Modules not applicable  0:
[CHIPSEC] *****************************************************************
~~~

2024-04-22 23:16 UTC, npmitche reviewed
At first glance this looks good. We'll need to take some time to test it out. 

Eventually we'll need to handle the case when this is attempted to be run in other environments.

2024-04-22 23:16 UTC, npmitche commented on chipsec/modules/tools/smm/smm_ptr.py
> +                if selfsmi_fuzz_iter(thread_id, _addr, _smi_desc):
Looks like you accidentally removed the `.` from this line.

2024-04-24 01:48 UTC, cpey commented on chipsec/modules/tools/smm/smm_ptr.py
> +            scan.add(duration, _smi_desc.smi_code, _smi_desc.smi_data, _smi_desc.gprs, contents_changed)
This is incorrect. 'duration' is initialized at line 447 when 'scan' is not None.

2024-05-07 19:16 UTC, cpey commented
Hi @npmitche, is there any progress on this?

2024-05-20 23:19 UTC, npmitche requested changes

2024-05-20 23:19 UTC, npmitche commented on chipsec/modules/tools/smm/smm_ptr.py
Will you please add in the "Examples" section (after line 73:
` >>> chipsec_main.py -m tools.smm.smm_ptr -a scan 0x0:0xff`

2024-05-21 23:34 UTC, npmitche approved these changes

2024-05-28 16:53 UTC, Sae86 approved these changes

2024-05-29 17:19 UTC, merged