Fix Bios Top Swap Test
chipsec/chipsec pull request #2205
Opened 2024-06-19 06:24 UTC by jun2zhou

2024-06-24 23:12 UTC, dscott90 commented on chipsec/cfg/8086/common.xml
> +    <control name="TopSwap"                register="BC"                  field="TS"                 desc="Top Swap"/>
```suggestion
    <control name="TopSwap"                register="BC"                   field="TS"                 desc="Top Swap"/>

```

2024-06-24 23:12 UTC, dscott90 approved these changes

2024-06-27 00:05 UTC, npmitche approved these changes

2024-06-27 00:07 UTC, npmitche requested changes
If the TS field is in the BC, the BC needs to be updated to include it. The BC in common.xml does not have it defined.
If this is for a specific platform, should modify the control there, not here.

2024-06-30 12:54 UTC, closed without merging